spring:
  reactor.debug-agent.enabled: false

spring.data.mongodb:
  database: orc-wf # Database name.
  host: orc_mongodb # Mongo server host.
  replicaSet: repDB # Mongo server host.
  port: 27017 # Mongo server port.
  repositories.enabled: true # Enable Mongo repositories.

logging.level.org:
  mongodb:
    driver:
      operation: DEBUG
