version: '3.4'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: "kafka"
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=orc-in-v1:1:1,orc-out-v1:1:1,orc-error-v1:1:1,orc-result-v1:1:1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=1099
    links:
      - zookeeper:zk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: "zookeeper"
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  orc_mongodb:
    #image: mongo
    build: .docker/mongodb
    container_name: "orc_mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=orc-wf
      - MONGO_NON_ROOT_ROLE=orc
      - MONGO_NON_ROOT_USERNAME=orc
      - MONGO_NON_ROOT_PASSWORD=orc
    volumes:
      - mongodb_data:/data/db
      #- ./.docker/mongodb/mongod.conf:/etc/mongod.conf
      - ./.docker/mongodb/mongo-init/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - 27017:27017
    #entrypoint: mongod --smallfiles --logpath=/dev/null --bind_ip_all --replSet repDB
    entrypoint: mongod --logpath=/dev/null --bind_ip_all --replSet repDB

  orc_mongo_express:
    image: mongo-express
    container_name: "orc_mongo_express"
    restart: always
    ports:
      - 8888:8081
    #links:
    #  - orc_mongodb
    depends_on:
      - orc_mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: orc_mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

  mailhog:
    container_name: "mailhog"
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  mongodb_data: